# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jcheck_rails}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Wilker Lucio"]
  s.date = %q{2010-08-17}
  s.description = %q{Generate jCheck code according to ActiveModel validations}
  s.email = %q{wilkerlucio@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.textile",
     "Rakefile",
     "VERSION",
     "init.rb",
     "jcheck_rails.gemspec",
     "lib/jcheck_rails.rb",
     "lib/jcheck_rails/encoder.rb",
     "spec/encoder_spec.rb",
     "spec/jcheck_rails_spec.rb",
     "spec/spec_helper.rb",
     "tasks/jcheck_tasks.rake"
  ]
  s.homepage = %q{http://github.com/wilkerlucio/jcheck_rails}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Generate jCheck code according to ActiveModel validations}
  s.test_files = [
    "spec/encoder_spec.rb",
     "spec/jcheck_rails_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<zip>, [">= 2.0.2"])
    else
      s.add_dependency(%q<zip>, [">= 2.0.2"])
    end
  else
    s.add_dependency(%q<zip>, [">= 2.0.2"])
  end
end

